[lighting]
light_type = "POINT"
location = [10, -10, 10]
energy = 10000

[camera]
location = [9.69, -5.85, 12.388]
rotation = [0.6799, 0.0, 0.8254]
lens = 20

[satellite]
satellite_file= "/models/nasa-aqua-satellite-obj/nasa-aqua-satellite.obj"

[background]
background_file= "/code/space.jpg"

[flightpath]
flight_path_type = "LINEAR" # 
positions = [[0,0,1],[1,6,1]]
rotations = [[0,0,0],[0.8,2.4,1.5]]

[animation]
animation_lenth = 15 # In seconds
file_format = "JPEG"
output_dir = "C:/Users/SteBa/Downloads/datapipeline4101/output/"