[lighting]
light_type = "POINT"
location = [10, -10, 10]
energy = 10000

[camera]
location = [0.0, -6.5, 0.0]
rotation = [1.5, 0.0, 0.0]
lens = 20

[satellite]
satellite_file= "/models/nasa-aqua-satellite-obj/nasa-aqua-satellite.obj"

[background]
background_file= "/code/space.jpg"

[flightpath]
flight_path_type = "FUNCTION" # 
positions = [[-10,0,0],[10,6,1]]
rotations = [[0,0,0],[0.8,2.4,1.5]]
x_eq = "t"
y_eq = "2*t**2"
z_eq = "0*t**2"

[animation]
animation_lenth = 10 # In seconds # add fps
file_format = "JPEG"
output_dir = "E:/tmp/"