[lighting]
# Lighting type "point" or "sun"
light_type = "POINT"
# Location of point source
location = (10, -10, 10)
# Strength of light source
energy = 1000

[satellite]
#path to satellite inside file
satellite_file= "/models/nasa-aqua-satellite.obj"

[background]
#path to satellite inside file
background_file= "/space.png"