[lighting]
light_type = "SUN"
location = [5, -500, 5]
energy = 10
roatation = [1.5, 0.0, 0.0]

[camera]
location = [0.0, -6.5, 0.0]
rotation = [1.5, 0.0, 0.0]
lens = 20
view_locked = true
lock_point = [0, 0, 0]


[satellite]
satellite_file= "/models/JunoOBJ/JunoOBJ/Juno.obj"
scale=2.0


[background]
background_file= "/code/space.jpg"
static_background=false

[earth]
earth_file = "/models/earth/Globe.obj"
earth_location = [10, 0, 0]
scale=0
use_earth=false


[stars]
star_seed=10
num_stars= 0
min_dist = -500
max_dist = 500
min_bright = 600
max_bright = 800
max_size = 0.25
min_size = 0.15

[flightpath]
flight_path_type = "POINT" # 
positions = [[0,0,0],[0,0,0]]
rotations = [[0,0,0],[0,50,0]]
x_eq = "0.0001*math.cos(t)"
y_eq = "0.01*math.sin(t/13)"
z_eq = "1"

[camera_flightpath]
flight_path_type = "FUNCTION" # 
positions = [[50,-15,0],[-100,-15,0]]
rotations = [[1.5, 0.0, 0.0],[1.5, 0.0, 0.0]]
x_eq = "15*math.cos(t/20.0)"
y_eq = "15*math.sin(t/20.0)"
z_eq = "0"

[animation]
animation_lenth = 5 # In seconds 
fps = 30
file_format = "JPEG"
output_dir = "E:/tmp/"